-- 068_platform_config_enums.sql
-- Platform-wide enum_values seeds + drop rigid CHECK constraints (varchar domains).
-- Regenerate inserts: node ad-west-api/scripts/gen-068-enum-sql.mjs

-- Drop CHECK constraints so values are configurable via enum_values.
-- Skips tables that do not exist yet (partial / older DB snapshots).
DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT * FROM (VALUES
      ('adwest', 'locations', 'chk_locations_level'),
      ('adwest', 'sthan_expenses', 'sthan_expenses_category_check'),
      ('adwest', 'sthan_expenses', 'sthan_expenses_status_check'),
      ('adwest', 'documents', 'chk_documents_access_level'),
      ('adwest', 'sreni_calendar_events', 'chk_sreni_calendar_scope'),
      ('adwest', 'report_submissions', 'chk_report_submissions_status'),
      ('adwest', 'report_template_fields', 'chk_report_template_field_type'),
      ('adwest', 'programs', 'chk_programs_status'),
      ('adwest', 'registrations', 'chk_registration_status'),
      ('adwest', 'attendance', 'chk_attendance_status'),
      ('adwest', 'approval_items', 'chk_approval_items_status'),
      ('adwest', 'approval_workflows', 'chk_approval_workflow_target_type'),
      ('adwest', 'report_metric_definitions', 'chk_report_metric_definitions_scope'),
      ('adwest', 'analytics_studio_layouts', 'chk_analytics_studio_layouts_type'),
      -- From 067 — household domains (safe to run even if 067 was skipped)
      ('adwest', 'srenies', 'chk_srenies_enrollment_scope'),
      ('adwest', 'srenies', 'chk_srenies_primary_contact_strategy'),
      ('adwest', 'household_members', 'chk_household_members_role'),
      ('adwest', 'household_members', 'chk_household_members_source')
    ) AS t(schema_name, table_name, constraint_name)
  LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = rec.schema_name AND table_name = rec.table_name
    ) THEN
      EXECUTE format(
        'ALTER TABLE %I.%I DROP CONSTRAINT IF EXISTS %I',
        rec.schema_name, rec.table_name, rec.constraint_name
      );
    END IF;
  END LOOP;
END;
$$;

INSERT INTO adwest.enum_values (id, enum_type, value, label, sort_order, active, parent_value, created_at, updated_at)
VALUES
  ('ev-admin_role-SUPER-ADMIN', 'admin_role', 'SUPER_ADMIN', 'Super Admin', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-admin_role-ZONE-ADMIN', 'admin_role', 'ZONE_ADMIN', 'Zone Admin', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-admin_role-SRENY-ADMIN', 'admin_role', 'SRENY_ADMIN', 'Sreny Admin', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-scope_type-global', 'scope_type', 'global', 'Global', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-scope_type-zone', 'scope_type', 'zone', 'Zone', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-scope_type-sreny', 'scope_type', 'sreny', 'Sreny', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-role_level-ZONE', 'role_level', 'ZONE', 'Zone', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-role_level-STHAN', 'role_level', 'STHAN', 'Sthan', 20, true, 'ZONE', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_mod-sequential', 'approval_mode', 'sequential', 'Sequential', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_mod-parallel', 'approval_mode', 'parallel', 'Parallel', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-primary_cont-HOUSEHOLD-HEAD', 'primary_contact_strategy', 'HOUSEHOLD_HEAD', 'Household head (one contact per row)', 10, true, 'household_head', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-primary_cont-FEMALE-PARTICIPANTS', 'primary_contact_strategy', 'FEMALE_PARTICIPANTS', 'Female participants (ladies Srenis)', 20, true, 'female_participants', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-primary_cont-ENROLLED-CHILDREN', 'primary_contact_strategy', 'ENROLLED_CHILDREN', 'Enrolled children (Bala Bharathi)', 30, true, 'enrolled_children', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-enrollment_s-HOUSEHOLD', 'enrollment_scope', 'HOUSEHOLD', 'Household-level division', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-enrollment_s-MEMBER', 'enrollment_scope', 'MEMBER', 'Per-member enrollment', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-household_me-head', 'household_member_role', 'head', 'Head of household', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-household_me-spouse', 'household_member_role', 'spouse', 'Spouse', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-household_me-child', 'household_member_role', 'child', 'Child', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-household_me-other', 'household_member_role', 'other', 'Other member', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-household_me-import', 'household_member_source', 'import', 'From Excel import', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-household_me-manual', 'household_member_source', 'manual', 'Added in app', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-female_gende-f', 'female_gender_match', 'f', 'f', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-female_gende-female', 'female_gender_match', 'female', 'Female', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-female_gende-woman', 'female_gender_match', 'woman', 'Woman', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-female_gende-women', 'female_gender_match', 'women', 'Women', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-location_lev-zone', 'location_level', 'zone', 'Zone', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-location_lev-sthan', 'location_level', 'sthan', 'Sthan', 20, true, 'zone', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-location_lev-division', 'location_level', 'division', 'Division', 30, true, 'sthan', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_cate-travel', 'expense_category', 'travel', 'Travel', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_cate-food', 'expense_category', 'food', 'Food & Meals', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_cate-accommodation', 'expense_category', 'accommodation', 'Accommodation', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_cate-event-supplies', 'expense_category', 'event_supplies', 'Event Supplies', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_cate-printing', 'expense_category', 'printing', 'Printing', 50, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_cate-other', 'expense_category', 'other', 'Other', 60, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_stat-draft', 'expense_status', 'draft', 'Draft', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_stat-submitted', 'expense_status', 'submitted', 'Submitted', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_stat-pending-review', 'expense_status', 'pending_review', 'Pending Review', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_stat-approved', 'expense_status', 'approved', 'Approved', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-expense_stat-rejected', 'expense_status', 'rejected', 'Rejected', 50, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_submi-monthly', 'report_submission_type', 'monthly', 'Monthly', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_submi-half-yearly', 'report_submission_type', 'half_yearly', 'Half-yearly', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_submi-yearly', 'report_submission_type', 'yearly', 'Yearly', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_metri-number', 'report_metric_input_type', 'number', 'Number', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_metri-text', 'report_metric_input_type', 'text', 'Text', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_metri-sreni', 'report_metric_scope', 'sreni', 'Sreni', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_metri-location', 'report_metric_scope', 'location', 'Location', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-sreni_report-draft', 'sreni_report_status', 'draft', 'Draft', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-sreni_report-submitted', 'sreni_report_status', 'submitted', 'Submitted', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_submi-pending', 'report_submission_status', 'pending', 'Pending', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_submi-approved', 'report_submission_status', 'approved', 'Approved', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_submi-rejected', 'report_submission_status', 'rejected', 'Rejected', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_templ-text', 'report_template_field_type', 'text', 'Text', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_templ-number', 'report_template_field_type', 'number', 'Number', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_templ-date', 'report_template_field_type', 'date', 'Date', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_templ-file', 'report_template_field_type', 'file', 'File', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-report_templ-dropdown', 'report_template_field_type', 'dropdown', 'Dropdown', 50, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-document_acc-sreny', 'document_access_level', 'sreny', 'Sreny', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-document_acc-zone', 'document_access_level', 'zone', 'Zone', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-document_acc-private', 'document_access_level', 'private', 'Private', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-calendar_eve-zone', 'calendar_event_scope', 'zone', 'Zone', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-calendar_eve-sthan', 'calendar_event_scope', 'sthan', 'Sthan', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-program_stat-draft', 'program_status', 'draft', 'Draft', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-program_stat-published', 'program_status', 'published', 'Published', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-program_stat-archived', 'program_status', 'archived', 'Archived', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-registration-registered', 'registration_status', 'registered', 'Registered', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-registration-waitlisted', 'registration_status', 'waitlisted', 'Waitlisted', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-registration-cancelled', 'registration_status', 'cancelled', 'Cancelled', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-attendance_s-present', 'attendance_state', 'present', 'Present', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-attendance_s-absent', 'attendance_state', 'absent', 'Absent', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-attendance_s-late', 'attendance_state', 'late', 'Late', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-attendance_s-excused', 'attendance_state', 'excused', 'Excused', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_tar-document-submission', 'approval_target_type', 'document_submission', 'Document submission', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_tar-report-submission', 'approval_target_type', 'report_submission', 'Report submission', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_tar-calendar-event', 'approval_target_type', 'calendar_event', 'Calendar event', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_ite-pending', 'approval_item_status', 'pending', 'Pending', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_ite-approved', 'approval_item_status', 'approved', 'Approved', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_ite-rejected', 'approval_item_status', 'rejected', 'Rejected', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_ite-need-more-informatio', 'approval_item_status', 'need_more_information', 'Need more information', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_dec-approved', 'approval_decision', 'approved', 'Approved', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_dec-rejected', 'approval_decision', 'rejected', 'Rejected', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-approval_dec-need-more-informatio', 'approval_decision', 'need_more_information', 'Need more information', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-general', 'helpdesk_ticket_category', 'general', 'General', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-technical', 'helpdesk_ticket_category', 'technical', 'Technical', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-financial', 'helpdesk_ticket_category', 'financial', 'Financial', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-membership', 'helpdesk_ticket_category', 'membership', 'Membership', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-other', 'helpdesk_ticket_category', 'other', 'Other', 50, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-open', 'helpdesk_ticket_status', 'open', 'Open', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-in-progress', 'helpdesk_ticket_status', 'in_progress', 'In Progress', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-resolved', 'helpdesk_ticket_status', 'resolved', 'Resolved', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-helpdesk_tic-closed', 'helpdesk_ticket_status', 'closed', 'Closed', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_posting_-full-time', 'job_posting_type', 'full_time', 'Full-time', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_posting_-part-time', 'job_posting_type', 'part_time', 'Part-time', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_posting_-contract', 'job_posting_type', 'contract', 'Contract', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_posting_-volunteer', 'job_posting_type', 'volunteer', 'Volunteer', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_applicat-new', 'job_application_status', 'new', 'New', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_applicat-under-review', 'job_application_status', 'under_review', 'Under Review', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_applicat-shortlisted', 'job_application_status', 'shortlisted', 'Shortlisted', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_applicat-rejected', 'job_application_status', 'rejected', 'Rejected', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-job_applicat-accepted', 'job_application_status', 'accepted', 'Accepted', 50, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-form_field_t-text', 'form_field_type', 'text', 'Text', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-form_field_t-number', 'form_field_type', 'number', 'Number', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-form_field_t-email', 'form_field_type', 'email', 'Email', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-form_field_t-phone', 'form_field_type', 'phone', 'Phone', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-form_field_t-date', 'form_field_type', 'date', 'Date', 50, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-form_field_t-select', 'form_field_type', 'select', 'Select', 60, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-form_field_t-checkbox', 'form_field_type', 'checkbox', 'Checkbox', 70, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-form_field_t-textarea', 'form_field_type', 'textarea', 'Textarea', 80, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-notification-all', 'notification_target', 'all', 'All members', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-notification-admin', 'notification_target', 'admin', 'Admins only', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-notification-member', 'notification_target', 'member', 'Members only', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-contact_livi-Family', 'contact_living_type', 'Family', 'Family', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-contact_livi-Bachelor', 'contact_living_type', 'Bachelor', 'Bachelor', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-contact_coun-UAE', 'contact_country', 'UAE', 'United Arab Emirates', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-contact_coun-India', 'contact_country', 'India', 'India', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-import_statu-processing', 'import_status', 'processing', 'Processing', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-import_statu-ready-for-review', 'import_status', 'ready_for_review', 'Ready for review', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-import_statu-finalized', 'import_status', 'finalized', 'Finalized', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-import_statu-failed', 'import_status', 'failed', 'Failed', 40, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-dedup_decisi-pending', 'dedup_decision', 'pending', 'Pending', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-dedup_decisi-merged', 'dedup_decision', 'merged', 'Merged', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-dedup_decisi-skipped', 'dedup_decision', 'skipped', 'Skipped', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-member_edit_-pending', 'member_edit_status', 'pending', 'Pending', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-member_edit_-approved', 'member_edit_status', 'approved', 'Approved', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-member_edit_-rejected', 'member_edit_status', 'rejected', 'Rejected', 30, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-analytics_la-details', 'analytics_layout_type', 'details', 'Details', 10, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')),
  ('ev-analytics_la-pivot', 'analytics_layout_type', 'pivot', 'Pivot', 20, true, NULL, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'))
ON CONFLICT (enum_type, value) DO UPDATE SET
  label = EXCLUDED.label,
  sort_order = EXCLUDED.sort_order,
  parent_value = EXCLUDED.parent_value,
  active = true,
  updated_at = EXCLUDED.updated_at;
