/** Human-readable labels for enum_type keys (Reference Data page + UI). */
export const ENUM_TYPE_LABELS: Record<string, string> = {
  admin_role: 'Admin Role',
  scope_type: 'Scope Type',
  role_level: 'Role Level',
  approval_mode: 'Approval Mode',
  primary_contact_strategy: 'Primary Contact Strategy',
  enrollment_scope: 'Enrollment Scope',
  household_member_role: 'Household Member Role',
  household_member_source: 'Household Member Source',
  female_gender_match: 'Female Gender Match',
  location_level: 'Location Level',
  expense_category: 'Expense Category',
  expense_status: 'Expense Status',
  report_submission_type: 'Report Submission Type',
  report_metric_input_type: 'Report Metric Input Type',
  report_metric_scope: 'Report Metric Scope',
  sreni_report_status: 'Sreni Report Status',
  report_submission_status: 'Report Submission Status',
  report_template_field_type: 'Report Template Field Type',
  document_access_level: 'Document Access Level',
  calendar_event_scope: 'Calendar Event Scope',
  program_status: 'Program Status',
  registration_status: 'Registration Status',
  attendance_state: 'Attendance State',
  approval_target_type: 'Approval Target Type',
  approval_item_status: 'Approval Item Status',
  approval_decision: 'Approval Decision',
  helpdesk_ticket_category: 'Helpdesk Ticket Category',
  helpdesk_ticket_status: 'Helpdesk Ticket Status',
  job_posting_type: 'Job Posting Type',
  job_application_status: 'Job Application Status',
  job_application_activity: 'Job Application Activity',
  form_field_type: 'Form Field Type',
  notification_target: 'Notification Target',
  contact_living_type: 'Contact Living Type',
  contact_country: 'Contact Country',
  import_status: 'Import Status',
  dedup_decision: 'Dedup Decision',
  member_edit_status: 'Member Edit Status',
  analytics_layout_type: 'Analytics Layout Type',
};

export const formatEnumTypeName = (t: string) =>
  ENUM_TYPE_LABELS[t] ?? t.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
